export const DEFAULT_CONFIG = [
    '+m_WaveData=(WaveNum=1, Enemies=((EnemyName=WarriorDroneWeak, Num=4)))',
    '+m_WaveData=(WaveNum=2, Enemies=((EnemyName=WarriorDroneWeak, Num=8)))',
    '+m_WaveData=(WaveNum=3, Enemies=((EnemyName=ShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=4, Enemies=((EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=5, Enemies=((EnemyName=WarriorDroneWeak, Num=6)), EnemiesSecondary=((EnemyName=StingerDroneNoShield, Num=4)), TimeToSpawnSecondary=5.f)',
    '+m_WaveData=(WaveNum=6, Enemies=((EnemyName=WarriorDroneWeak, Num=4), (EnemyName=ShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=7, Enemies=((EnemyName=WarriorDroneWeak, Num=6), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=8, Enemies=((EnemyName=TankDrone, Num=2)))',
    '+m_WaveData=(WaveNum=9, Enemies=((EnemyName=ShieldDrone, Num=2), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=10, Enemies=((EnemyName=TankDrone, Num=3)))',
    '+m_WaveData=(WaveNum=11, Enemies=((EnemyName=WarriorDrone, Num=6)))',
    '+m_WaveData=(WaveNum=12, Enemies=((EnemyName=WarriorDrone, Num=4), (EnemyName=ShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=13, Enemies=((EnemyName=RedShieldDrone, Num=2), (EnemyName=GrenadeDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=14, Enemies=((EnemyName=BlueShieldDrone, Num=2), (EnemyName=StingerDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=15, Enemies=((EnemyName=WarriorDroneWeak, Num=4), (EnemyName=TankDrone, Num=1)))',
    '+m_WaveData=(WaveNum=16, Enemies=((EnemyName=WarriorDrone, Num=4), (EnemyName=ChainsawDrone, Num=3)))',
    '+m_WaveData=(WaveNum=17, Enemies=((EnemyName=ShieldDrone, Num=2), (EnemyName=RedShieldDrone, Num=1)))',
    '+m_WaveData=(WaveNum=18, Enemies=((EnemyName=BlueShieldDrone, Num=1), (EnemyName=RedShieldDrone, Num=1)))',
    '+m_WaveData=(WaveNum=19, Enemies=((EnemyName=WarriorDroneWeak, Num=12)))',
    '+m_WaveData=(WaveNum=20, Enemies=((EnemyName=Poison, Num=1)))',
    '+m_WaveData=(WaveNum=21, Enemies=((EnemyName=WarriorDrone, Num=4), (EnemyName=WarriorDroneHeavy, Num=4)))',
    '+m_WaveData=(WaveNum=22, Enemies=((EnemyName=WarriorDroneHeavy, Num=4), (EnemyName=ShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=23, Enemies=((EnemyName=FlyingDrone, Num=3)))',
    '+m_WaveData=(WaveNum=24, Enemies=((EnemyName=FlyingDrone, Num=3), (EnemyName=StingerDrone, Num=3)))',
    '+m_WaveData=(WaveNum=25, Enemies=((EnemyName=ShieldDrone, Num=1), (EnemyName=ChainsawDrone, Num=1), (EnemyName=TankDrone, Num=1)))',
    '+m_WaveData=(WaveNum=26, Enemies=((EnemyName=BabyRage, Num=8)))',
    '+m_WaveData=(WaveNum=27, Enemies=((EnemyName=rage, Num=2)))',
    '+m_WaveData=(WaveNum=28, Enemies=((EnemyName=rage, Num=1), (EnemyName=AngelRage, Num=1)))',
    '+m_WaveData=(WaveNum=29, Enemies=((EnemyName=rage, Num=1), (EnemyName=DemonRage, Num=1)))',
    '+m_WaveData=(WaveNum=30, Enemies=((EnemyName=AngelRage, Num=1), (EnemyName=DemonRage, Num=1)))',
    '+m_WaveData=(WaveNum=31, Enemies=((EnemyName=WarriorDroneWeak, Num=10)))',
    '+m_WaveData=(WaveNum=32, Enemies=((EnemyName=WarriorDroneHeavy, Num=3), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=33, Enemies=((EnemyName=WarriorDroneHeavy, Num=4), (EnemyName=FlyingDrone, Num=3)))',
    '+m_WaveData=(WaveNum=34, Enemies=((EnemyName=ShieldDrone, Num=2), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=35, Enemies=((EnemyName=WarriorDroneHeavy, Num=6), (EnemyName=ShieldDrone, Num=3)))',
    '+m_WaveData=(WaveNum=36, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=GrenadeDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=37, Enemies=((EnemyName=FlyingDrone, Num=4), (EnemyName=GrenadeDroneNoShield, Num=6)))',
    '+m_WaveData=(WaveNum=38, Enemies=((EnemyName=TankDrone, Num=2), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=39, Enemies=((EnemyName=WarriorDroneWeak, Num=6), (EnemyName=StingerDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=40, Enemies=((EnemyName=Hunter, Num=1)))',
    '+m_WaveData=(WaveNum=41, Enemies=((EnemyName=DreamRunner, Num=1)))',
    '+m_WaveData=(WaveNum=42, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=StingerDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=43, Enemies=((EnemyName=WarriorDroneHeavy, Num=3), (EnemyName=ShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=44, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=BlueShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=45, Enemies=((EnemyName=RedShieldDrone, Num=4), (EnemyName=GrenadeDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=46, Enemies=((EnemyName=BuzzsawTank, Num=1)))',
    '+m_WaveData=(WaveNum=47, Enemies=((EnemyName=WarriorDroneHeavy, Num=4)), EnemiesSecondary=((EnemyName=FlyingDrone, Num=4)), TimeToSpawnSecondary=8.f)',
    '+m_WaveData=(WaveNum=48, Enemies=((EnemyName=BabyRage, Num=8)), EnemiesSecondary=((EnemyName=rage, Num=2)), TimeToSpawnSecondary=10.f)',
    '+m_WaveData=(WaveNum=49, Enemies=((EnemyName=WarriorDroneWeak, Num=16)))',
    '+m_WaveData=(WaveNum=50, Enemies=((EnemyName=DreamRunner, Num=2)))',
    '+m_WaveData=(WaveNum=51, Enemies=((EnemyName=WarriorDroneWeak, Num=6)))',
    '+m_WaveData=(WaveNum=52, Enemies=((EnemyName=WarriorDrone, Num=4), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=53, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=BlueShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=54, Enemies=((EnemyName=WarriorDrone, Num=4), (EnemyName=RedShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=55, Enemies=((EnemyName=BlueShieldDrone, Num=2), (EnemyName=RedShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=56, Enemies=((EnemyName=BlueShieldDrone, Num=2), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=57, Enemies=((EnemyName=AngelRage, Num=1), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=58, Enemies=((EnemyName=RedShieldDrone, Num=1), (EnemyName=DemonRage, Num=1)))',
    '+m_WaveData=(WaveNum=59, Enemies=((EnemyName=WarriorDrone, Num=10), (EnemyName=GrenadeDroneNoShield, Num=6)))',
    '+m_WaveData=(WaveNum=60, Enemies=((EnemyName=KillingFace, Num=1)))',
    '+m_WaveData=(WaveNum=61, Enemies=((EnemyName=WarriorDrone, Num=4), (EnemyName=WarriorDroneHeavy, Num=4)))',
    '+m_WaveData=(WaveNum=62, Enemies=((EnemyName=WarriorDroneHeavy, Num=4), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=63, Enemies=((EnemyName=ShieldDrone, Num=2), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=64, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=StingerDrone, Num=4)))',
    '+m_WaveData=(WaveNum=65, Enemies=((EnemyName=StingerDroneNoShield, Num=20)))',
    '+m_WaveData=(WaveNum=66, Enemies=((EnemyName=ChainsawDrone, Num=2), (EnemyName=TankDrone, Num=2)))',
    '+m_WaveData=(WaveNum=67, Enemies=((EnemyName=WarriorDroneWeak, Num=10), (EnemyName=BuzzsawTank, Num=1)))',
    '+m_WaveData=(WaveNum=68, Enemies=((EnemyName=BabyRage, Num=8)))',
    '+m_WaveData=(WaveNum=69, Enemies=((EnemyName=BabyRage, Num=8), (EnemyName=rage, Num=2)))',
    '+m_WaveData=(WaveNum=70, Enemies=((EnemyName=BuzzsawTank, Num=1), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=71, Enemies=((EnemyName=WarriorDroneWeak, Num=6), (EnemyName=WarriorDroneHeavy, Num=4)))',
    '+m_WaveData=(WaveNum=72, Enemies=((EnemyName=WarriorDroneWeak, Num=6), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=73, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=RedShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=74, Enemies=((EnemyName=WarriorDroneHeavy, Num=2), (EnemyName=FlyingDrone, Num=4)))',
    '+m_WaveData=(WaveNum=75, Enemies=((EnemyName=WarriorDroneWeak, Num=3), (EnemyName=StingerDroneNoShield, Num=2)))',
    '+m_WaveData=(WaveNum=76, Enemies=((EnemyName=FlyingDrone, Num=4), (EnemyName=StingerDroneNoShield, Num=4)))',
    '+m_WaveData=(WaveNum=77, Enemies=((EnemyName=BlueShieldDrone, Num=2), (EnemyName=StingerDrone, Num=2)))',
    '+m_WaveData=(WaveNum=78, Enemies=((EnemyName=RedShieldDrone, Num=2), (EnemyName=GrenadeDrone, Num=2)))',
    '+m_WaveData=(WaveNum=79, Enemies=((EnemyName=WarriorDrone, Num=8)))',
    '+m_WaveData=(WaveNum=80, Enemies=((EnemyName=BobBarbas, Num=1)))',
    '+m_WaveData=(WaveNum=81, Enemies=((EnemyName=BabyRage, Num=10)))',
    '+m_WaveData=(WaveNum=82, Enemies=((EnemyName=rage, Num=1), (EnemyName=DemonRage, Num=1)))',
    '+m_WaveData=(WaveNum=83, Enemies=((EnemyName=WarriorDroneWeak, Num=6)), EnemiesSecondary=((EnemyName=AngelRage, Num=2)), TimeToSpawnSecondary=8.f)',
    '+m_WaveData=(WaveNum=84, Enemies=((EnemyName=RedShieldDrone, Num=2)), EnemiesSecondary=((EnemyName=DemonRage, Num=2)), TimeToSpawnSecondary=5.f)',
    '+m_WaveData=(WaveNum=85, Enemies=((EnemyName=Summoner, Num=1), (EnemyName=DreamRunner, Num=1)))',
    '+m_WaveData=(WaveNum=86, Enemies=((EnemyName=ShieldDrone, Num=3)))',
    '+m_WaveData=(WaveNum=87, Enemies=((EnemyName=ShieldDrone, Num=2), (EnemyName=BlueShieldDrone, Num=1)))',
    '+m_WaveData=(WaveNum=88, Enemies=((EnemyName=RedShieldDrone, Num=1), (EnemyName=ChainsawDrone, Num=2)))',
    '+m_WaveData=(WaveNum=89, Enemies=((EnemyName=WarriorDroneHeavy, Num=5), (EnemyName=Summoner, Num=1)))',
    '+m_WaveData=(WaveNum=90, Enemies=((EnemyName=DreamRunner, Num=1)))',
    '+m_WaveData=(WaveNum=91, Enemies=((EnemyName=ShieldDrone, Num=5)))',
    '+m_WaveData=(WaveNum=92, Enemies=((EnemyName=BlueShieldDrone, Num=2), (EnemyName=RedShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=93, Enemies=((EnemyName=ChainsawDrone, Num=4)))',
    '+m_WaveData=(WaveNum=94, Enemies=((EnemyName=StingerDroneNoShield, Num=8)))',
    '+m_WaveData=(WaveNum=95, Enemies=((EnemyName=WarriorDrone, Num=6), (EnemyName=ShieldDrone, Num=2)))',
    '+m_WaveData=(WaveNum=96, Enemies=((EnemyName=TankDrone, Num=2)))',
    '+m_WaveData=(WaveNum=97, Enemies=((EnemyName=AngelRage, Num=1), (EnemyName=DemonRage, Num=1)))',
    '+m_WaveData=(WaveNum=98, Enemies=((EnemyName=BuzzsawTank, Num=1), (EnemyName=DreamRunner, Num=1)))',
    '+m_WaveData=(WaveNum=99, Enemies=((EnemyName=WarriorDroneWeak, Num=10), (EnemyName=GrenadeDroneNoShield, Num=10)))',
    '+m_WaveData=(WaveNum=100, Enemies=((EnemyName=Mundus, Num=1)))',
    '+m_WaveData=(WaveNum=101, Enemies=((EnemyName=Vergil, Num=1)))',
];

export const dmcColumns = [
    {
        title: '名称',
        dataIndex: 'name',
        key: 'name',
    },
    {
        title: '英文名',
        dataIndex: 'engName',
        key: 'engName',
    },
    {
        title: '难度',
        dataIndex: 'difficulty',
        key: 'difficulty',
        align: 'center',
        render: (value, record) => {
            if (record.isBoss) {
                return 'boss'
            } else {
                return value
            }
        }
    },
];

export const dmcDataSource=[
    {
        key: '1',
        name: '小冥',
        engName: 'WarriorDroneWeak',
        difficulty: 1,
        isBoss: false,
    }, {
        key: '2',
        name: '死亡骑士',
        engName: 'ShieldDrone',
        difficulty: 5,
        isBoss: false,
    }, {
        key: '3',
        name: '电锯',
        engName: 'ChainsawDrone',
        difficulty: 6,
        isBoss: false,
    }, {
        key: '4',
        name: '激光豆丁',
        engName: 'StingerDroneNoShield',
        difficulty: 2,
        isBoss: false,
    }, {
        key: '5',
        name: '暴君',
        engName: 'TankDrone',
        difficulty: 9,
        isBoss: false,
    }, {
        key: '6',
        name: '中冥',
        engName: 'WarriorDrone',
        difficulty: 3,
        isBoss: false,
    }, {
        key: '7',
        name: '火骑士',
        engName: 'RedShieldDrone',
        difficulty: 7,
        isBoss: false,
    }, {
        key: '8',
        name: '炸弹豆丁',
        engName: 'GrenadeDroneNoShield',
        difficulty: 2,
        isBoss: false,
    }, {
        key: '9',
        name: '冰骑士',
        engName: 'BlueShieldDrone',
        difficulty: 7,
        isBoss: false,
    }, {
        key: '10',
        name: '大冥',
        engName: 'WarriorDroneHeavy',
        difficulty: 4,
        isBoss: false,
    }, {
        key: '30',
        name: '鸟人',
        engName: 'FlyingDrone',
        difficulty: 5,
        isBoss: false,
    }, {
        key: '11',
        name: '带盾激光豆丁',
        engName: 'StingerDrone',
        difficulty: 4,
        isBoss: false,
    }, {
        key: '12',
        name: '带盾炸弹豆丁',
        engName: 'StingerDroneNoShield',
        difficulty: 3,
        isBoss: false,
    }, {
        key: '13',
        name: '小老鼠',
        engName: 'BabyRage',
        difficulty: 1,
        isBoss: false,
    }, {
        key: '14',
        name: '老鼠',
        engName: 'rage',
        difficulty: 6,
        isBoss: false,
    }, {
        key: '15',
        name: '蓝老鼠',
        engName: 'AngelRage',
        difficulty: 8,
        isBoss: false,
    }, {
        key: '16',
        name: '红老鼠',
        engName: 'DemonRage',
        difficulty: 8,
        isBoss: false,
    }, {
        key: '17',
        name: '双刀',
        engName: 'DreamRunner',
        difficulty: 10,
        isBoss: false,
    }, {
        key: '18',
        name: '屠夫',
        engName: 'BuzzsawTank',
        difficulty: 9,
        isBoss: false,
    }, {
        key: '19',
        name: '女巫',
        engName: 'WarriorDrone',
        difficulty: 10,
        isBoss: false,
    }, {
        key: '20',
        name: '魅魔',
        engName: 'Poison',
        difficulty: 11,
        isBoss: true,
    }, {
        key: '21',
        name: '猎人 ',
        engName: 'Hunter',
        difficulty: 12,
        isBoss: true,
    }, {
        key: '22',
        name: '曼达斯之子',
        engName: 'KillingFace',
        difficulty: 13,
        isBoss: true,
    }, {
        key: '23',
        name: '鲍勃',
        engName: 'BobBarbas',
        difficulty: 14,
        isBoss: true,
    }, {
        key: '24',
        name: '曼达斯',
        engName: 'Mundus',
        difficulty: 15,
        isBoss: true,
    }, {
        key: '25',
        name: '维吉尔',
        engName: 'Vergil',
        difficulty: 16,
        isBoss: true,
    },
].sort((first, second) => first.difficulty - second.difficulty);
